package mesh.protocol

import com.google.protobuf.ByteString
import java.security.SecureRandom

object PacketFactory {
    const val DEFAULT_TTL = 8
    const val DEFAULT_LIFETIME_MS = 24 * 60 * 60 * 1000L // 24 hours
    const val MSG_ID_SIZE_BYTES = 16

    private val secureRandom = SecureRandom()

    fun generateMsgId(): ByteArray {
        val id = ByteArray(MSG_ID_SIZE_BYTES)
        secureRandom.nextBytes(id)
        return id
    }

    /**
     * Creates a new DATA packet.
     *
     * @param origin the originating node ID
     * @param dest the destination node ID, or null for broadcast
     * @param payload the data payload bytes
     * @param msgId optional 16-byte message ID (randomly generated by default)
     * @param ttl remaining hops (default 8)
     * @param hopCount hops travelled so far (default 0)
     * @param createdAtMs creation timestamp in epoch ms
     * @param expiresAtMs expiration timestamp in epoch ms
     */
    fun createData(
        origin: NodeId,
        dest: NodeId?,
        payload: ByteArray,
        msgId: ByteArray = generateMsgId(),
        ttl: Int = DEFAULT_TTL,
        hopCount: Int = 0,
        createdAtMs: Long = System.currentTimeMillis(),
        expiresAtMs: Long = createdAtMs + DEFAULT_LIFETIME_MS
    ): Packet {
        require(msgId.size == MSG_ID_SIZE_BYTES) {
            "msgId must be exactly $MSG_ID_SIZE_BYTES bytes"
        }
        return Packet.newBuilder()
            .setMsgId(ByteString.copyFrom(msgId))
            .setOrigin(origin.toByteString())
            .apply {
                if (dest != null) {
                    setDest(dest.toByteString())
                } else {
                    setDest(ByteString.EMPTY)
                }
            }
            .setType(PacketType.DATA)
            .setTtl(ttl)
            .setHopCount(hopCount)
            .setCreatedAtMs(createdAtMs)
            .setExpiresAtMs(expiresAtMs)
            .setPayload(ByteString.copyFrom(payload))
            .build()
    }

    /**
     * Creates an ACK packet in response to a received packet.
     *
     * @param origin this node's ID
     * @param dest the destination node ID (original sender of the packet being acknowledged)
     * @param ackedMsgId the 16-byte message ID of the acknowledged packet (stored in payload)
     * @param msgId optional 16-byte message ID for this ACK packet
     * @param ttl remaining hops (default 8)
     * @param hopCount hops travelled so far (default 0)
     * @param createdAtMs creation timestamp in epoch ms
     * @param expiresAtMs expiration timestamp in epoch ms
     */
    fun createAck(
        origin: NodeId,
        dest: NodeId,
        ackedMsgId: ByteArray,
        msgId: ByteArray = generateMsgId(),
        ttl: Int = DEFAULT_TTL,
        hopCount: Int = 0,
        createdAtMs: Long = System.currentTimeMillis(),
        expiresAtMs: Long = createdAtMs + DEFAULT_LIFETIME_MS
    ): Packet {
        require(ackedMsgId.size == MSG_ID_SIZE_BYTES) {
            "ackedMsgId must be exactly $MSG_ID_SIZE_BYTES bytes"
        }
        require(msgId.size == MSG_ID_SIZE_BYTES) {
            "msgId must be exactly $MSG_ID_SIZE_BYTES bytes"
        }
        return Packet.newBuilder()
            .setMsgId(ByteString.copyFrom(msgId))
            .setOrigin(origin.toByteString())
            .setDest(dest.toByteString())
            .setType(PacketType.ACK)
            .setTtl(ttl)
            .setHopCount(hopCount)
            .setCreatedAtMs(createdAtMs)
            .setExpiresAtMs(expiresAtMs)
            .setPayload(ByteString.copyFrom(ackedMsgId))
            .build()
    }

    /**
     * Creates a HELLO packet containing peer discovery data (display name and public key).
     */
    fun createHello(
        origin: NodeId,
        displayName: String,
        publicKey: ByteArray,
        msgId: ByteArray = generateMsgId(),
        ttl: Int = 1, // HELLO is direct neighbour discovery (hop 1)
        createdAtMs: Long = System.currentTimeMillis(),
        expiresAtMs: Long = createdAtMs + (60 * 1000L) // HELLO short lifetime (e.g., 60s)
    ): Packet {
        val payloadBytes = HelloPayload(displayName, publicKey).encode()
        return createHelloRaw(
            origin = origin,
            payload = payloadBytes,
            msgId = msgId,
            ttl = ttl,
            createdAtMs = createdAtMs,
            expiresAtMs = expiresAtMs
        )
    }

    /**
     * Creates a HELLO packet with arbitrary raw payload bytes.
     */
    fun createHelloRaw(
        origin: NodeId,
        payload: ByteArray,
        msgId: ByteArray = generateMsgId(),
        ttl: Int = 1,
        createdAtMs: Long = System.currentTimeMillis(),
        expiresAtMs: Long = createdAtMs + (60 * 1000L)
    ): Packet {
        require(msgId.size == MSG_ID_SIZE_BYTES) {
            "msgId must be exactly $MSG_ID_SIZE_BYTES bytes"
        }
        return Packet.newBuilder()
            .setMsgId(ByteString.copyFrom(msgId))
            .setOrigin(origin.toByteString())
            .setDest(ByteString.EMPTY) // Broadcast to immediate neighbours
            .setType(PacketType.HELLO)
            .setTtl(ttl)
            .setHopCount(0)
            .setCreatedAtMs(createdAtMs)
            .setExpiresAtMs(expiresAtMs)
            .setPayload(ByteString.copyFrom(payload))
            .build()
    }

    /**
     * Creates a SYNC_SUMMARY packet containing bloom filter bytes for anti-entropy sync.
     */
    fun createSyncSummary(
        origin: NodeId,
        dest: NodeId,
        bloomFilterBytes: ByteArray,
        msgId: ByteArray = generateMsgId(),
        ttl: Int = 1, // Direct peer anti-entropy
        createdAtMs: Long = System.currentTimeMillis(),
        expiresAtMs: Long = createdAtMs + (5 * 60 * 1000L) // 5 minutes
    ): Packet {
        require(msgId.size == MSG_ID_SIZE_BYTES) {
            "msgId must be exactly $MSG_ID_SIZE_BYTES bytes"
        }
        return Packet.newBuilder()
            .setMsgId(ByteString.copyFrom(msgId))
            .setOrigin(origin.toByteString())
            .setDest(dest.toByteString())
            .setType(PacketType.SYNC_SUMMARY)
            .setTtl(ttl)
            .setHopCount(0)
            .setCreatedAtMs(createdAtMs)
            .setExpiresAtMs(expiresAtMs)
            .setPayload(ByteString.copyFrom(bloomFilterBytes))
            .build()
    }
}
